"""
blender_param_editor.py
=======================
Blender パラメータエディタ

【機能】
- N-Panel (Nキー) の「GE3 Sync」タブにスライダーUIを表示
- ボス・プレイヤーのパラメータをBlenderから操作できる
- 「Apply to Game」ボタンで blender_params.txt に書き出し
  → ゲームが60フレームごとに読み込んで即座に反映！

【対応パラメータ】
- boss_z_offset  : ボスとの距離
- boss_y_offset  : ボスの高さ
- boss_scale     : ボスのスケール
- player_speed_x : プレイヤーX方向速度
- player_speed_y : プレイヤーY方向速度
- player_limit_x : プレイヤー移動限界X
- player_limit_y : プレイヤー移動限界Y
- boss_hp        : ボスHP (デバッグ用)
- player_hp      : プレイヤーHP (デバッグ用)

【使い方】
1. このスクリプトを実行
2. Nパネル(Nキー)の「GE3 Sync」タブを開く
3. スライダーでパラメータを調整
4. 「Apply to Game」を押すとゲームに即反映！
"""

import bpy
import os
import json
from bpy.types import Panel, Operator, PropertyGroup
from bpy.props import FloatProperty, PointerProperty

# ──────────────────────────────────────────
# 設定
# ──────────────────────────────────────────
PARAMS_PATH     = r"C:\Users\k024g\Desktop\GE3&CG3\project\Resources\blender_params.txt"
GAME_STATE_PATH = r"C:\Users\k024g\Desktop\GE3&CG3\project\Resources\game_state.json"
# ──────────────────────────────────────────


class GE3ParamProperties(PropertyGroup):
    """パラメータのプロパティグループ"""
    boss_z_offset:  FloatProperty(name="Boss Z Offset",   default=169.0, min=10.0,  max=500.0,  description="Distance between player and boss")
    boss_y_offset:  FloatProperty(name="Boss Y Height",   default=10.0,  min=-50.0, max=100.0,  description="Boss height offset")
    boss_scale:     FloatProperty(name="Boss Scale",      default=3.0,   min=0.1,   max=20.0,   description="Boss overall scale")
    player_speed_x: FloatProperty(name="Player Speed X",  default=80.0,  min=1.0,   max=200.0,  description="Player horizontal speed")
    player_speed_y: FloatProperty(name="Player Speed Y",  default=50.0,  min=1.0,   max=200.0,  description="Player vertical speed")
    player_limit_x: FloatProperty(name="Player Limit X",  default=20.0,  min=5.0,   max=50.0,   description="Player movement limit X")
    player_limit_y: FloatProperty(name="Player Limit Y",  default=12.0,  min=5.0,   max=30.0,   description="Player movement limit Y")
    boss_hp:        FloatProperty(name="Boss HP",         default=500.0, min=0.0,   max=5000.0, description="Boss current HP (debug)")
    player_hp:      FloatProperty(name="Player HP",       default=100.0, min=0.0,   max=1000.0, description="Player current HP (debug)")


class GE3_OT_ApplyParams(Operator):
    """パラメータをblender_params.txtに書き出してゲームに送信する"""
    bl_idname  = "ge3.apply_params"
    bl_label   = "Apply to Game"
    bl_options = {"REGISTER"}

    def execute(self, context):
        props = context.scene.ge3_params
        lines = [
            "# GE3 Blender Parameter Export",
            "# This file is auto-generated by blender_param_editor.py",
            f"boss_z_offset={props.boss_z_offset:.2f}",
            f"boss_y_offset={props.boss_y_offset:.2f}",
            f"boss_scale={props.boss_scale:.2f}",
            f"player_speed_x={props.player_speed_x:.2f}",
            f"player_speed_y={props.player_speed_y:.2f}",
            f"player_limit_x={props.player_limit_x:.2f}",
            f"player_limit_y={props.player_limit_y:.2f}",
            f"boss_hp={props.boss_hp:.1f}",
            f"player_hp={props.player_hp:.1f}",
        ]
        with open(PARAMS_PATH, "w") as f:
            f.write("\n".join(lines) + "\n")

        self.report({"INFO"}, f"Parameters sent to game! ({PARAMS_PATH})")
        print(f"[Param Editor] Applied {len(lines)-2} parameters to game.")
        return {"FINISHED"}


class GE3_OT_ReadFromGame(Operator):
    """game_state.json から現在のゲーム状態を読み込んでパラメータを同期する"""
    bl_idname  = "ge3.read_from_game"
    bl_label   = "Sync from Game"
    bl_options = {"REGISTER"}

    def execute(self, context):
        if not os.path.exists(GAME_STATE_PATH):
            self.report({"WARNING"}, "game_state.json not found. Is the game running?")
            return {"CANCELLED"}

        try:
            with open(GAME_STATE_PATH, "r") as f:
                state = json.load(f)
        except Exception as e:
            self.report({"ERROR"}, f"Failed to read game state: {e}")
            return {"CANCELLED"}

        props = context.scene.ge3_params

        # プレイヤーHPの同期
        if "player" in state:
            props.player_hp = state["player"].get("hp", props.player_hp)

        # ボスHPの同期
        if "boss" in state:
            props.boss_hp = state["boss"].get("hp", props.boss_hp)

        self.report({"INFO"}, "Synced HP values from running game!")
        print("[Param Editor] Synced from game_state.json")
        return {"FINISHED"}


class GE3_OT_ResetParams(Operator):
    """パラメータをデフォルト値に戻す"""
    bl_idname  = "ge3.reset_params"
    bl_label   = "Reset to Default"
    bl_options = {"REGISTER", "UNDO"}

    def execute(self, context):
        props = context.scene.ge3_params
        props.boss_z_offset  = 169.0
        props.boss_y_offset  = 10.0
        props.boss_scale     = 3.0
        props.player_speed_x = 25.0
        props.player_speed_y = 20.0
        props.player_limit_x = 20.0
        props.player_limit_y = 12.0
        props.boss_hp        = 500.0
        props.player_hp      = 100.0
        self.report({"INFO"}, "Reset to default values.")
        return {"FINISHED"}


class GE3_PT_ParamEditorPanel(Panel):
    """N-Panel の「GE3 Sync」タブ内のパラメータエディタUI"""
    bl_label       = "GE3 Param Editor"
    bl_idname      = "GE3_PT_ParamEditorPanel"
    bl_space_type  = "VIEW_3D"
    bl_region_type = "UI"
    bl_category    = "GE3 Sync"

    def draw(self, context):
        layout = self.layout
        props  = context.scene.ge3_params

        # ── ゲーム状態同期ボタン ──
        row = layout.row()
        row.operator("ge3.read_from_game", icon="FILE_REFRESH")

        layout.separator()

        # ── ボスパラメータ ──
        box = layout.box()
        box.label(text="Boss Parameters", icon="ARMATURE_DATA")
        col = box.column(align=True)
        col.prop(props, "boss_z_offset", slider=True)
        col.prop(props, "boss_y_offset", slider=True)
        col.prop(props, "boss_scale",    slider=True)
        col.prop(props, "boss_hp",       slider=True)

        layout.separator()

        # ── プレイヤーパラメータ ──
        box2 = layout.box()
        box2.label(text="Player Parameters", icon="PERSON")
        col2 = box2.column(align=True)
        col2.prop(props, "player_speed_x", slider=True)
        col2.prop(props, "player_speed_y", slider=True)
        col2.prop(props, "player_limit_x", slider=True)
        col2.prop(props, "player_limit_y", slider=True)
        col2.prop(props, "player_hp",      slider=True)

        layout.separator()

        # ── 適用・リセットボタン ──
        row2 = layout.row(align=True)
        row2.scale_y = 1.5
        row2.operator("ge3.apply_params",  icon="EXPORT")
        row2.operator("ge3.reset_params",  icon="LOOP_BACK")

        layout.separator()
        layout.label(text="Output: blender_params.txt", icon="FILE_TEXT")
        layout.label(text="Game reads every 60 frames.")


classes = [
    GE3ParamProperties,
    GE3_OT_ApplyParams,
    GE3_OT_ReadFromGame,
    GE3_OT_ResetParams,
    GE3_PT_ParamEditorPanel,
]


def register():
    for cls in classes:
        bpy.utils.register_class(cls)
    bpy.types.Scene.ge3_params = PointerProperty(type=GE3ParamProperties)
    print("[Param Editor] Registered! Check N-Panel > 'GE3 Sync' tab.")


def unregister():
    for cls in reversed(classes):
        bpy.utils.unregister_class(cls)
    if hasattr(bpy.types.Scene, "ge3_params"):
        del bpy.types.Scene.ge3_params


if __name__ == "__main__":
    # 再登録（スクリプト再実行時のクリーンアップ）
    try:
        unregister()
    except Exception:
        pass
    register()
    print("[Param Editor] Ready! Open N-Panel > 'GE3 Sync' tab.")
